---
title: "Replication 2"
author: "Enxhi Buxheli"
date: "2/17/2019"
output: 
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# attaching libraries
library(dplyr)
library(janitor)
library(tidyverse)
library(xtable)
library(RItools)
library(ri)

# eliminates junk output from xtable
options(xtable.comment = FALSE)

# Loading in the data using read_csv instead of read.csv
pnas_data   <- read_csv("dataverse_files/pnas_data.csv")
t1_data     <- read_csv("dataverse_files/t1_data.csv")
prime_data  <- read_csv("dataverse_files/prime_data.csv")
confed_data <- read_csv("dataverse_files/confederate_face_data.csv")
hisp_data   <- read_csv("dataverse_files/hispanic_face_data.csv")
white_data  <- read_csv("dataverse_files/white_face_data.csv")
```

# Table 1
```{r}
# output.vars <- c('numberim','Remain','Englishlan')
# var.names   <- c('Number of immigrants be increased?',
#                  'Children of undocumented be allowed to stay?',
#                  'English as official language?')
# 
# # Creates the whole matrix
# final.mat.use = rbind(final.mat.main,final.mat.prime)
# final.mat.use$greater.p.value = as.numeric(as.character(final.mat.use$greater.p.value)) final.mat.use$lesser.p.value = as.numeric(as.character(final.mat.use$lesser.p.value)) 
# final.mat.use$ate = as.numeric(as.character(final.mat.use$ate))
# final.mat.use$x.mean = as.numeric(as.character(final.mat.use$x.mean))
# final.mat.use$x.sd = as.numeric(as.character(final.mat.use$x.sd))
# final.mat.use$N = as.numeric(as.character(final.mat.use$N))
# final.mat.use$p.value = final.mat.use$greater.p.value
# 
# # Redcats variables and properly formats them
# final.mat.redact = final.mat.use[,c('variable','subset','ate','p.value','x.mean','x.sd','N')]
# final.mat.redact[,c('ate','p.value','x.mean','x.sd')] = round(final.mat.redact[,c('ate','p.value','x.mean','x.sd')],3)
# final.mat.redact$ate.new = paste(final.mat.redact$ate,' (',final.mat.redact$p.value,')',sep='')
# final.mat.redact$x.mean.new = paste(final.mat.redact$x.mean,' (',final.mat.redact$x.sd,')',sep='')
# 
# out.mat.a <- filter(final.mat.redact, subset == 'all', final.mat.redact$variable %in% output.vars)
# out.mat.a = final.mat.redact[final.mat.redact$subset == 'all'&final.mat.redact$variable %in% output.vars,]
# out.mat.a = final.mat.redact[final.mat.redact$subset == 'all'&final.mat.redact$variable %in% output.vars,c('ate.new')]	
# out.mat.c = final.mat.redact[final.mat.redact$subset == 'no.car'&final.mat.redact$variable %in% output.vars,c('ate.new')]
# out.mat.x = final.mat.redact[final.mat.redact$subset == 'all'&final.mat.redact$variable %in% output.vars,c('x.mean.new')]
#  Ns = c('N',max(final.mat.redact$N[final.mat.redact$subset=='all']),
# 	max(final.mat.redact$N[final.mat.redact$subset=='no.car']),
# 	max(final.mat.redact$N[final.mat.redact$subset=='all'])
# 	)
# 
#  h1 = c('',paste('(',1:3,')',sep = ''))
#  h2 = c('','all respondents','waits on platform','all respondents')
#  h3 = c('question','ATE (p)','CATE (p)','T1 levels (sd)')
#  hs = rbind(h1,h2,h3)
#  row.names(hs) = NULL
# 	
#  out.mat = cbind(out.mat.a,cbind(out.mat.c,out.mat.x))
#  out.mat = cbind(var.names,out.mat)
#  out.mat = rbind(out.mat,Ns)
#  
#  out.mat = rbind(hs,out.mat)
#  out.table = xtable(out.mat, digits = 3)
#  
# out.table
```


# Table 2
```{r, results='asis'}
## Here I used the balance_check.r code and compared the balance_table.tex output to the 
## original article to ensure that the results were replicated. Here, I am just putting it
## all together in a code chunk. I maintained the majority of their variable names and here
## just changed the code so that it would use read_csv instead of read.csv. I also eliminated
## some of the other analyses that Enos had run which was not necessary for performing the 
## replication. The xBalance function is used to calculate the standardized mean differences 
## from each covariate.
balance_table <- xBalance(treatment ~ liberal+republican+obama.disapprove+ride.everyday+voted.2010+romney.voter+Hispanics.x+age+residency.new+college+male+hispanic.new+white+income.new, 
                            data = pnas_data, 
                            report = c("std.diffs","z.scores","adj.means","chisquare.test")[1:3], 
                            strata = factor(pnas_data$station))

## Outputs the results for Table 2 in the replication document. 
balance_xtable <- xtable(balance_table$results[,1:4,], 
                         label="Table 2. Covariate balance across treatment conditions", 
                         digits=2,
                         align = "lrrrr")

# Adding user friendly names/labels in the final table 2
rownames(balance_xtable) <- c("Liberal†", "Republican", "Obama disapprove", "Ride MBTA every day", "Voted 2010", "Romney voter", "Hispanic threat", "Age", "Residency year", "College", "Male", "Hispanic", "White", "Income")
colnames(balance_xtable) <- c("Control", "Treatment", "Standard Difference", "Z Score")

# ## Comments to be added to the footnotes of the xtable: ATTEMPTED TO BE AMENDED
# comment <- list(pos = list(0), command = NULL)
# comment$pos[[1]] <- c(nrow(balance_xtable))
# comment$command  <- c("\\footnotesize {*Difference in standardized units.}")

print(balance_xtable,
      hline.after = c(0, nrow(balance_xtable + 2)),
      #add.to.row = comment,
      floating = TRUE)
```



